### ISSUE TITLE
Client notes field is truncated

### ISSUE THREAD

**Issue by timsk** [Cambridge-Community-Kitchen/cck-volunteer-web-app#19]
The "client notes" field appears to be truncated at ~192 chars when it's imported from the Clients & Deliveries spreadsheet. Please allow up to 1000 chars.

If a concrete example is needed, today's notes (2023-03-16) for client "N", starting "If main dish contains...", end abruptly with the partial word "verball". The last sentence from the spreadsheet cell is omitted.

**Comment by faceless-stoat** [comment]
I think this is the same issue as #15?

**Comment by faceless-stoat** [comment]
Closing this as a duplicate of #15.
